config/routes.rb
Rails.application.routes.draw do
	
  # get "/" :categories, only: [:show]
  resources :categories, only: [:show, :index]

  resources :pages, only: [:show]
  
  get "/page/:id/api" => "pages#show_json", defaults: { format: "json" }

  root "pages#index"

  namespace :admin do
  	resources :categories
    resources :pages  # admin/pages
  end

  Page.where.not("slug", nil).all.each do |page|
  	get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :category
end

app/controllers/admin/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/admin/pages_controller.rb
module Admin

  class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    # GET /pages
    # GET /pages.json
    def index
      @pages = Page.all
    end

    # GET /pages/1
    # GET /pages/1.json
    def show
    end

    # GET /pages/new
    def new
      @page = Page.new
    end

    # GET /pages/1/edit
    def edit
    end

    # POST /pages
    # POST /pages.json
    def create
      @page = Page.new(page_params)

      respond_to do |format|
        if @page.save
          format.html { redirect_to admin_page_path(@page), notice: 'Page was successfully created.' }
          format.json { render :show, status: :created, location: @page }
        else
          format.html { render :new }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /pages/1
    # PATCH/PUT /pages/1.json
    def update
      respond_to do |format|
        if @page.update(page_params)
          format.html { redirect_to admin_page_path(@page), notice: 'Page was successfully updated.' }
          format.json { render :show, status: :ok, location: @page }
        else
          format.html { render :edit }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /pages/1
    # DELETE /pages/1.json
    def destroy
      @page.destroy
      respond_to do |format|
        format.html { redirect_to admin_pages_url, notice: 'Page was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def page_params
        params.require(:page).permit(:title, :body, :slug, :category_id)
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.includes(:pages).find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set, only: [:show]	

  def index
  	@pages = Page.paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def create
  end

  def show_json
  	@page = Page.find(params[:id])
    # @page = Page.paginate(:page => params[:page], :per_page => 30)

  	respond_to do |format|
  	  format.json { render json: @page.to_json }
  	end
  end

  private

    def set
      @page = Page.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def url_for_page(page)
 	if page.slug.present?
 	  page.slug
 	else
 	  "pages/#{page.id}"	
 	end
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/admin/pages/_form.html.erb
<%= form_for(['admin', @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div>
    <%= f.label :category_id %><br>
    <%= f.select :category_id, Category.all.map { |category| [ category.name, category.id ] }, class: "form-controll" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.body %></td>
        <td><%= url_for_page page %></td>
        <td><%= link_to 'Show', admin_page_path(page) %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
        <td><%= link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<% @category.pages.each do |page| %>
	<h2> <%= link_to page.title, url_for_page(page) %> </h2>
	<p> <%=page.created_at.to_formatted_s :long %> </p>
	<%= page.body.html_safe %>
	<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cmsruby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages</h1>

<ul>
	<% @pages.each do |page| %>
	<li> <%= link_to page.title, page %> </li>
	<% end %>

	<%= will_paginate @pages %>
</ul>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<p> 
	<em><%= time_ago_in_words @page.created_at %> </em>
</p>


<!-- 
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %> -->